// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Messages struct {
	ID        int64         `json:"id"`
	RoomID    sql.NullInt64 `json:"room_id"`
	UserID    sql.NullInt64 `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Rooms struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Users struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
