// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateRoom(ctx context.Context, name string) (Rooms, error) {
	row := q.db.QueryRowContext(ctx, createRoom, name)
	var i Rooms
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
